name: Test Suite
run-name: ${{ github.actor }} is running the tests
on: [ push ]
jobs:
  PHP:
    strategy:
      matrix:
        php: [ '8.2' ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run the test suite
        run: vendor/bin/phpunit
